version: 0.2
phases:
  pre_build:
    commands:
      - terraform init -reconfigure -backend-config=$BACKEND_CONFIG
      - terraform validate
  
  build:
    commands:
      - terraform plan -var-file $TF_VARS -out "deploy.plan"
      - terraform apply "deploy.plan"