version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip3 install --upgrade aws-sam-cli
  build:
    commands:
      - sam build --parameter-overrides=$SAM_VARS
  post_build:
    commands:
      - sam package --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
    - configuration.json
